package main

import (
	"flag"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

type generatorPlugin interface {
	Files() []*protogen.File
}

type serviceInfo struct {
	serviceName string
	clientName  string
	importPath  string
}

func main() {
	var flags flag.FlagSet
	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		// Collect all services across all files
		var allServices []*serviceInfo
		var allFiles []*protogen.File

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			allFiles = append(allFiles, f)
			services := generateFile(gen, f)
			allServices = append(allServices, services...)
		}

		// Only generate wrapper if this is the last file (alphabetically last proto file)
		// This is a workaround since protoc calls the plugin per-file
		var lastFile *protogen.File
		for _, f := range gen.Files {
			if f.Generate && (lastFile == nil || f.Proto.GetName() > lastFile.Proto.GetName()) {
				lastFile = f
			}
		}

		if len(allServices) > 0 && lastFile != nil {
			generateWrapperClient(gen, allServices, allFiles, lastFile)
		}

		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) []*serviceInfo {
	if len(file.Services) == 0 {
		return nil
	}

	var services []*serviceInfo

	// Generate one client file per service
	for _, service := range file.Services {
		info := generateServiceClient(gen, file, service)
		generateServiceServerDefinition(gen, file, service)
		services = append(services, info)
	}

	return services
}

func toLowerCamel(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func basePathFromFile(file *protogen.File) string {
	// Derive a stable basePath from proto filename:
	// proto/idp_users.proto -> /idp-users
	name := filepath.Base(file.Proto.GetName())
	name = strings.TrimSuffix(name, filepath.Ext(name))
	name = strings.ReplaceAll(name, "_", "-")
	if strings.HasPrefix(name, "/") {
		return name
	}
	return "/" + name
}

func generateServiceServerDefinition(gen *protogen.Plugin, file *protogen.File, service *protogen.Service) {
	// Output: proto/idp_users_service.ts (source-relative)
	filename := file.GeneratedFilenamePrefix + "_service.ts"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	serviceName := service.GoName
	basePath := basePathFromFile(file)

	// Import the generated protobuf types
	pbImport := "./" + strings.TrimSuffix(file.GeneratedFilenamePrefix[strings.LastIndex(file.GeneratedFilenamePrefix, "/")+1:], "") + "_pb"

	g.P("// Code generated by protoc-gen-ts-client. DO NOT EDIT.")
	g.P()

	// Import types only
	g.P("import type {")
	for _, method := range service.Methods {
		g.P("  ", method.Input.GoIdent.GoName, ",")
		g.P("  ", method.Output.GoIdent.GoName, ",")
	}
	g.P("} from '", pbImport, "';")
	g.P()

	// Import schemas (values, not types)
	g.P("import {")
	for _, method := range service.Methods {
		g.P("  ", method.Input.GoIdent.GoName, "Schema,")
		g.P("  ", method.Output.GoIdent.GoName, "Schema,")
	}
	g.P("} from '", pbImport, "';")
	g.P()

	// Minimal framework-agnostic context type that matches the server framework shape
	g.P("export type HandlerContext<TAuth = unknown, TAudit = unknown> = {")
	g.P("  auth: TAuth;")
	g.P("  audit: TAudit;")
	g.P("  requestId?: string;")
	g.P("};")
	g.P()

	// Generate handler interface
	g.P("export interface ", serviceName, "Handlers<TAuth = unknown, TAudit = unknown> {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		handlerName := toLowerCamel(method.GoName)
		g.P("  ", handlerName, "(ctx: HandlerContext<TAuth, TAudit>, req: ", method.Input.GoIdent.GoName, "): Promise<", method.Output.GoIdent.GoName, ">;")
	}
	g.P("}")
	g.P()

	// Runtime metadata for generic routing/serialization
	g.P("export const ", serviceName, "Runtime = {")
	g.P("  basePath: '", basePath, "',")
	g.P("  serviceName: '", serviceName, "',")
	g.P("  methods: {")
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		handlerName := toLowerCamel(method.GoName)
		g.P("    ", method.GoName, ": {")
		g.P("      name: '", method.GoName, "',")
		g.P("      handlerName: '", handlerName, "',")
		g.P("      requestSchema: ", method.Input.GoIdent.GoName, "Schema,")
		g.P("      responseSchema: ", method.Output.GoIdent.GoName, "Schema,")
		g.P("    },")
	}
	g.P("  },")
	g.P("} as const;")
}

func generateServiceClient(gen *protogen.Plugin, file *protogen.File, service *protogen.Service) *serviceInfo {
	// Output: domains/v1/domains_client.ts
	filename := file.GeneratedFilenamePrefix + "_client.ts"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	serviceName := service.GoName
	clientName := serviceName + "Client"

	// Store service info for wrapper generation
	info := &serviceInfo{
		serviceName: serviceName,
		clientName:  clientName,
		importPath:  "./" + file.GeneratedFilenamePrefix + "_client",
	}

	// Import the generated protobuf types
	pbImport := "./" + strings.TrimSuffix(file.GeneratedFilenamePrefix[strings.LastIndex(file.GeneratedFilenamePrefix, "/")+1:], "") + "_pb"

	g.P("// Code generated by protoc-gen-ts-client. DO NOT EDIT.")
	g.P()

	// Import Message type to exclude its metadata fields from request parameters
	g.P("import type { Message } from '@bufbuild/protobuf';")
	g.P("import { create, toJson, fromJson } from '@bufbuild/protobuf';")
	g.P()

	// Import types only
	g.P("import type {")
	for _, method := range service.Methods {
		g.P("  ", method.Input.GoIdent.GoName, ",")
		g.P("  ", method.Output.GoIdent.GoName, ",")
	}
	g.P("} from '", pbImport, "';")
	g.P()

	// Import schemas (values, not types)
	g.P("import {")
	for _, method := range service.Methods {
		g.P("  ", method.Input.GoIdent.GoName, "Schema,")
		g.P("  ", method.Output.GoIdent.GoName, "Schema,")
	}
	g.P("} from '", pbImport, "';")
	g.P()

	// Generate clean data-only type aliases for each request type
	g.P("// Request types without protobuf Message metadata")
	for _, method := range service.Methods {
		inputType := method.Input.GoIdent.GoName
		dataType := inputType + "Data"
		g.P("type ", dataType, " = Omit<", inputType, ", keyof Message>;")
	}
	g.P()

	// Client configuration interface
	g.P("export interface ", clientName, "Config {")
	g.P("  endpoint: string;")
	g.P("  authorization?: string;")
	g.P("  /** Custom fetch function for request interceptors, token refresh, retry logic, etc. */")
	g.P("  fetch?: typeof fetch;")
	g.P("}")
	g.P()
	// Extract service comment from proto file
	serviceComment := string(service.Comments.Leading)
	g.P("/**")
	if strings.TrimSpace(serviceComment) != "" {
		for _, line := range strings.Split(strings.TrimSpace(serviceComment), "\n") {
			g.P(" * ", strings.TrimPrefix(strings.TrimSpace(line), "//"))
		}
	} else {
		g.P(" * ", serviceName, " client - AWS SDK-style client for ", serviceName)
	}
	g.P(" */")
	g.P("export class ", clientName, " {")
	g.P("  private readonly endpoint: string;")
	g.P("  private readonly authorization?: string;")
	g.P("  private readonly fetch: typeof fetch;")
	g.P()
	g.P("  constructor(config: ", clientName, "Config) {")
	g.P("    this.endpoint = config.endpoint.replace(/\\/$/, '');")
	g.P("    this.authorization = config.authorization;")
	g.P("    this.fetch = config.fetch || globalThis.fetch.bind(globalThis);")
	g.P("  }")
	g.P()

	// Generate methods
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}

		methodName := method.GoName
		// Convert to camelCase for TypeScript
		tsMethodName := strings.ToLower(methodName[:1]) + methodName[1:]
		inputType := method.Input.GoIdent.GoName
		outputType := method.Output.GoIdent.GoName

		// Check if the request has any required (non-optional) fields
		hasRequiredFields := false
		for _, field := range method.Input.Fields {
			if !field.Desc.HasOptionalKeyword() && !field.Desc.IsList() && !field.Desc.IsMap() {
				hasRequiredFields = true
				break
			}
		}

		// Use the clean data-only type alias (without Message metadata)
		// Only make parameter optional if there are NO required fields
		dataOnlyType := inputType + "Data"
		requestParam := "request: " + dataOnlyType
		if !hasRequiredFields {
			// No required fields, make parameter optional with default empty object
			requestParam = "request?: " + dataOnlyType
		}

		// Extract method comment from proto file
		methodComment := string(method.Comments.Leading)
		if strings.TrimSpace(methodComment) == "" {
			methodComment = ""
		}

		g.P("  /**")
		if methodComment != "" {
			for _, line := range strings.Split(strings.TrimSpace(methodComment), "\n") {
				g.P("   * ", strings.TrimPrefix(strings.TrimSpace(line), "//"))
			}
		} else {
			g.P("   * ", methodName, " - Send ", methodName, " request")
		}
		g.P("   */")
		g.P("  async ", tsMethodName, "(", requestParam, "): Promise<", outputType, "> {")
		g.P("    const headers: Record<string, string> = {")
		g.P("      'Content-Type': 'application/json',")
		g.P("    };")
		g.P()
		g.P("    if (this.authorization) {")
		g.P("      headers['Authorization'] = this.authorization;")
		g.P("    }")
		g.P()
		g.P("    const requestMessage = create(", inputType, "Schema, request || {});")
		g.P("    const response = await this.fetch(`${this.endpoint}/", methodName, "`, {")
		g.P("      method: 'POST',")
		g.P("      headers,")
		g.P("      body: JSON.stringify(toJson(", inputType, "Schema, requestMessage)),")
		g.P("    });")
		g.P()
		g.P("    if (!response.ok) {")
		g.P("      const error = await response.text();")
		g.P("      throw new Error(`", methodName, " failed: ${response.status} ${error}`);")
		g.P("    }")
		g.P()
		g.P("    const responseData = (await response.json()) as any;")
		g.P("    return fromJson(", outputType, "Schema, responseData);")
		g.P("  }")
		g.P()
	}

	g.P("}")
	g.P()

	// Re-export all types from the protobuf file
	g.P("// Re-export types from protobuf")
	g.P("export * from '", pbImport, "';")

	return info
}

func generateWrapperClient(gen *protogen.Plugin, services []*serviceInfo, files []*protogen.File, file *protogen.File) {
	// Generate client.ts at root output directory (empty import path)
	g := gen.NewGeneratedFile("client.ts", "")

	g.P("// Code generated by protoc-gen-ts-client. DO NOT EDIT.")
	g.P()

	// Import all service clients
	g.P("import {")
	for _, svc := range services {
		g.P("  ", svc.clientName, ",")
	}
	g.P("} from './index';")
	g.P()

	// Wrapper client config
	g.P("export interface ClientConfig {")
	g.P("  baseUrl: string;")
	g.P("  authorization?: string;")
	g.P("  /** Custom fetch function for request interceptors, token refresh, retry logic, etc. */")
	g.P("  fetch?: typeof fetch;")
	g.P("}")
	g.P()

	// Wrapper client class
	g.P("/**")
	g.P(" * Unified client for all services")
	g.P(" */")
	g.P("export class Client {")

	// Service properties
	for _, svc := range services {
		// Convert DomainsService -> domains, EmailIdentitiesService -> emailIdentities
		propName := strings.ToLower(svc.serviceName[:1]) + strings.TrimSuffix(svc.serviceName[1:], "Service")
		g.P("  readonly ", propName, ": ", svc.clientName, ";")
	}
	g.P()

	// Constructor
	g.P("  constructor(config: ClientConfig) {")
	g.P("    const { baseUrl, authorization, fetch } = config;")
	g.P()

	for _, svc := range services {
		propName := strings.ToLower(svc.serviceName[:1]) + strings.TrimSuffix(svc.serviceName[1:], "Service")
		// Extract service path from serviceName: DomainsService -> domains, EmailIdentitiesService -> email-identities
		servicePath := strings.TrimSuffix(svc.serviceName, "Service")
		// Handle camelCase to kebab-case: emailIdentities -> email-identities
		servicePath = camelToKebab(servicePath)

		g.P("    this.", propName, " = new ", svc.clientName, "({")
		g.P("      endpoint: `${baseUrl}/", servicePath, "`,")
		g.P("      authorization,")
		g.P("      fetch,")
		g.P("    });")
	}

	g.P("  }")
	g.P("}")

	// Generate index.ts that exports everything
	idx := gen.NewGeneratedFile("index.ts", "")
	idx.P("// Code generated by protoc-gen-ts-client. DO NOT EDIT.")
	idx.P()

	// Export all service clients
	for _, svc := range services {
		idx.P("export { ", svc.clientName, " } from '", svc.importPath, "';")
	}
	idx.P()

	// Export all types from protobuf-generated files
	for _, f := range files {
		pbFile := f.GeneratedFilenamePrefix + "_pb"
		idx.P("export * from './" + pbFile + "';")
	}
	idx.P()

	idx.P("export { Client, type ClientConfig } from './client';")
}

func camelToKebab(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteRune('-')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
