package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		params := parseParams(plugin.Request.GetParameter())
		if params["client_mode"] == "external" {
			generateExternalClient(plugin, params)
			return nil
		}

		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func parseParams(param string) map[string]string {
	result := map[string]string{}
	if param == "" {
		return result
	}
	for _, part := range strings.Split(param, ",") {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		k, v, ok := strings.Cut(part, "=")
		if !ok {
			result[part] = ""
			continue
		}
		result[k] = v
	}
	return result
}

func generateExternalClient(plugin *protogen.Plugin, params map[string]string) {
	clientPackage := params["client_package"]
	if clientPackage == "" {
		clientPackage = "adminclient"
	}

	filename := params["client_filename"]
	if filename == "" {
		filename = "admin_api_http_client.pb.go"
	}

	compoundEnabled := params["compound_client"] == "true"
	compoundFilename := params["compound_client_filename"]
	if compoundFilename == "" {
		compoundFilename = "admin_api_client.pb.go"
	}

	// NOTE: We intentionally generate a single file to avoid duplicating shared helper
	// types across multiple proto packages.
	g := plugin.NewGeneratedFile(filename, protogen.GoImportPath(""))

	g.P("// Code generated by protoc-gen-go-http-client. DO NOT EDIT.")
	g.P("// source: admin-api protos")
	g.P()
	g.P("package ", clientPackage)
	g.P()

	g.P("import (")
	g.P("\t\"bytes\"")
	g.P("\t\"context\"")
	g.P("\t\"fmt\"")
	g.P("\t\"io\"")
	g.P("\t\"net/http\"")
	g.P("\t\"strings\"")
	g.P("\t\"unicode\"")
	g.P()
	g.P("\t\"google.golang.org/protobuf/encoding/protojson\"")
	g.P("\t\"google.golang.org/protobuf/proto\"")
	g.P(")")
	g.P()

	// Shared helper types (keeps client usable as SDK without extra deps).
	g.P("type BearerTokenProvider interface {")
	g.P("\tBearerToken(ctx context.Context) (string, error)")
	g.P("}")
	g.P()
	g.P("type StaticBearerToken string")
	g.P()
	g.P("func (t StaticBearerToken) BearerToken(ctx context.Context) (string, error) {")
	g.P("\treturn string(t), nil")
	g.P("}")
	g.P()

	g.P("type ClientOption func(*clientOptions)")
	g.P("type clientOptions struct {")
	g.P("\thttpClient    *http.Client")
	g.P("\ttokenProvider BearerTokenProvider")
	g.P("}")
	g.P()

	g.P("func WithHTTPClient(httpClient *http.Client) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.httpClient = httpClient }")
	g.P("}")
	g.P()
	g.P("func WithBearerToken(token string) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.tokenProvider = StaticBearerToken(token) }")
	g.P("}")
	g.P()
	g.P("func WithBearerTokenProvider(provider BearerTokenProvider) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.tokenProvider = provider }")
	g.P("}")
	g.P()

	g.P("func normalizeBaseURL(baseURL string) string {")
	g.P("\treturn strings.TrimSuffix(baseURL, \"/\")")
	g.P("}")
	g.P()

	g.P("func kebabCaseServicePath(serviceName string) string {")
	g.P("\tname := strings.TrimSuffix(serviceName, \"Service\")")
	g.P("\tvar b strings.Builder")
	g.P("\tfor i, r := range name {")
	g.P("\t\tif unicode.IsUpper(r) {")
	g.P("\t\t\tif i != 0 {")
	g.P("\t\t\t\tb.WriteByte('-')")
	g.P("\t\t\t}")
	g.P("\t\t\tb.WriteRune(unicode.ToLower(r))")
	g.P("\t\t\tcontinue")
	g.P("\t\t}")
	g.P("\t\tb.WriteRune(r)")
	g.P("\t}")
	g.P("\treturn \"/\" + b.String()")
	g.P("}")
	g.P()

	g.P("func doProtoJSONCall(ctx context.Context, httpClient *http.Client, tokenProvider BearerTokenProvider, baseURL string, servicePath string, methodName string, req proto.Message, resp proto.Message) error {")
	g.P("\tif httpClient == nil {")
	g.P("\t\thttpClient = &http.Client{}")
	g.P("\t}")
	g.P("\tbaseURL = normalizeBaseURL(baseURL)")
	g.P("\turl := baseURL + servicePath + \"/\" + methodName")
	g.P()
	g.P("\tbody, err := protojson.MarshalOptions{}.Marshal(req)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"marshal request: %w\", err)")
	g.P("\t}")
	g.P()
	g.P("\thttpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"build request: %w\", err)")
	g.P("\t}")
	g.P("\thttpReq.Header.Set(\"Content-Type\", \"application/json\")")
	g.P("\tif tokenProvider != nil {")
	g.P("\t\ttoken, err := tokenProvider.BearerToken(ctx)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\treturn fmt.Errorf(\"get bearer token: %w\", err)")
	g.P("\t\t}")
	g.P("\t\tif token != \"\" {")
	g.P("\t\t\thttpReq.Header.Set(\"Authorization\", \"Bearer \"+token)")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
	g.P("\thttpResp, err := httpClient.Do(httpReq)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"do request: %w\", err)")
	g.P("\t}")
	g.P("\tdefer httpResp.Body.Close()")
	g.P()
	g.P("\trespBody, err := io.ReadAll(httpResp.Body)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"read response: %w\", err)")
	g.P("\t}")
	g.P()
	g.P("\tif httpResp.StatusCode != http.StatusOK {")
	g.P("\t\treturn fmt.Errorf(\"http %s %s failed: status=%d body=%q\", servicePath, methodName, httpResp.StatusCode, string(respBody))")
	g.P("\t}")
	g.P()
	g.P("\tif resp == nil {")
	g.P("\t\treturn nil")
	g.P("\t}")
	g.P("\tif len(respBody) == 0 {")
	g.P("\t\treturn nil")
	g.P("\t}")
	g.P("\tif err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, resp); err != nil {")
	g.P("\t\treturn fmt.Errorf(\"unmarshal response: %w\", err)")
	g.P("\t}")
	g.P("\treturn nil")
	g.P("}")
	g.P()

	services := collectGeneratedServices(plugin)

	for _, s := range services {
		generateServiceClientExternal(g, s.file, s.service)
	}

	if compoundEnabled {
		generateCompoundClientExternal(plugin, compoundFilename, clientPackage, services)
	}
}

type generatedService struct {
	file    *protogen.File
	service *protogen.Service
}

func collectGeneratedServices(plugin *protogen.Plugin) []generatedService {
	var services []generatedService
	for _, file := range plugin.Files {
		if !file.Generate {
			continue
		}
		if len(file.Services) == 0 {
			continue
		}
		for _, service := range file.Services {
			services = append(services, generatedService{file: file, service: service})
		}
	}
	sort.Slice(services, func(i, j int) bool {
		return services[i].service.GoName < services[j].service.GoName
	})
	return services
}

func generateCompoundClientExternal(plugin *protogen.Plugin, filename string, clientPackage string, services []generatedService) {
	g := plugin.NewGeneratedFile(filename, protogen.GoImportPath(""))

	g.P("// Code generated by protoc-gen-go-http-client. DO NOT EDIT.")
	g.P("// source: admin-api protos")
	g.P()
	g.P("package ", clientPackage)
	g.P()
	g.P("import (\"net/http\")")
	g.P()

	g.P("type Client struct {")
	for _, s := range services {
		fieldName := strings.TrimSuffix(s.service.GoName, "Service")
		if fieldName == "" {
			fieldName = s.service.GoName
		}
		g.P("\t", fieldName, " *", s.service.GoName, "Client")
	}
	g.P("}")
	g.P()

	g.P("func NewClient(baseURL string, opts ...ClientOption) *Client {")
	g.P("\to := &clientOptions{httpClient: &http.Client{}}")
	g.P("\tfor _, opt := range opts {")
	g.P("\t\tif opt != nil {")
	g.P("\t\t\topt(o)")
	g.P("\t\t}")
	g.P("\t}")
	g.P("\tshared := []ClientOption{WithHTTPClient(o.httpClient)}")
	g.P("\tif o.tokenProvider != nil {")
	g.P("\t\tshared = append(shared, WithBearerTokenProvider(o.tokenProvider))")
	g.P("\t}")
	g.P("\treturn &Client{")
	for _, s := range services {
		fieldName := strings.TrimSuffix(s.service.GoName, "Service")
		if fieldName == "" {
			fieldName = s.service.GoName
		}
		g.P("\t\t", fieldName, ": New", s.service.GoName, "Client(baseURL, shared...),")
	}
	g.P("\t}")
	g.P("}")
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_http_client.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-http-client. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	g.P("import (")
	g.P("\t\"bytes\"")
	g.P("\t\"context\"")
	g.P("\t\"fmt\"")
	g.P("\t\"io\"")
	g.P("\t\"net/http\"")
	g.P("\t\"strings\"")
	g.P("\t\"unicode\"")
	g.P()
	g.P("\t\"google.golang.org/protobuf/encoding/protojson\"")
	g.P("\t\"google.golang.org/protobuf/proto\"")
	g.P(")")
	g.P()

	// Shared helper types per package (keeps client usable as SDK without extra deps).
	g.P("type BearerTokenProvider interface {")
	g.P("\tBearerToken(ctx context.Context) (string, error)")
	g.P("}")
	g.P()
	g.P("type StaticBearerToken string")
	g.P()
	g.P("func (t StaticBearerToken) BearerToken(ctx context.Context) (string, error) {")
	g.P("\treturn string(t), nil")
	g.P("}")
	g.P()

	g.P("type ClientOption func(*clientOptions)")
	g.P("type clientOptions struct {")
	g.P("\thttpClient    *http.Client")
	g.P("\ttokenProvider BearerTokenProvider")
	g.P("}")
	g.P()

	g.P("func WithHTTPClient(httpClient *http.Client) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.httpClient = httpClient }")
	g.P("}")
	g.P()
	g.P("func WithBearerToken(token string) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.tokenProvider = StaticBearerToken(token) }")
	g.P("}")
	g.P()
	g.P("func WithBearerTokenProvider(provider BearerTokenProvider) ClientOption {")
	g.P("\treturn func(o *clientOptions) { o.tokenProvider = provider }")
	g.P("}")
	g.P()

	g.P("func normalizeBaseURL(baseURL string) string {")
	g.P("\treturn strings.TrimSuffix(baseURL, \"/\")")
	g.P("}")
	g.P()

	g.P("func kebabCaseServicePath(serviceName string) string {")
	g.P("\tname := strings.TrimSuffix(serviceName, \"Service\")")
	g.P("\tvar b strings.Builder")
	g.P("\tfor i, r := range name {")
	g.P("\t\tif unicode.IsUpper(r) {")
	g.P("\t\t\tif i != 0 {")
	g.P("\t\t\t\tb.WriteByte('-')")
	g.P("\t\t\t}")
	g.P("\t\t\tb.WriteRune(unicode.ToLower(r))")
	g.P("\t\t\tcontinue")
	g.P("\t\t}")
	g.P("\t\tb.WriteRune(r)")
	g.P("\t}")
	g.P("\treturn \"/\" + b.String()")
	g.P("}")
	g.P()

	g.P("func doProtoJSONCall(ctx context.Context, httpClient *http.Client, tokenProvider BearerTokenProvider, baseURL string, servicePath string, methodName string, req proto.Message, resp proto.Message) error {")
	g.P("\tif httpClient == nil {")
	g.P("\t\thttpClient = &http.Client{}")
	g.P("\t}")
	g.P("\tbaseURL = normalizeBaseURL(baseURL)")
	g.P("\turl := baseURL + servicePath + \"/\" + methodName")
	g.P()
	g.P("\tbody, err := protojson.MarshalOptions{}.Marshal(req)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"marshal request: %w\", err)")
	g.P("\t}")
	g.P()
	g.P("\thttpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"build request: %w\", err)")
	g.P("\t}")
	g.P("\thttpReq.Header.Set(\"Content-Type\", \"application/json\")")
	g.P("\tif tokenProvider != nil {")
	g.P("\t\ttoken, err := tokenProvider.BearerToken(ctx)")
	g.P("\t\tif err != nil {")
	g.P("\t\t\treturn fmt.Errorf(\"get bearer token: %w\", err)")
	g.P("\t\t}")
	g.P("\t\tif token != \"\" {")
	g.P("\t\t\thttpReq.Header.Set(\"Authorization\", \"Bearer \"+token)")
	g.P("\t\t}")
	g.P("\t}")
	g.P()
	g.P("\thttpResp, err := httpClient.Do(httpReq)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"do request: %w\", err)")
	g.P("\t}")
	g.P("\tdefer httpResp.Body.Close()")
	g.P()
	g.P("\trespBody, err := io.ReadAll(httpResp.Body)")
	g.P("\tif err != nil {")
	g.P("\t\treturn fmt.Errorf(\"read response: %w\", err)")
	g.P("\t}")
	g.P()
	g.P("\tif httpResp.StatusCode != http.StatusOK {")
	g.P("\t\treturn fmt.Errorf(\"http %s %s failed: status=%d body=%q\", servicePath, methodName, httpResp.StatusCode, string(respBody))")
	g.P("\t}")
	g.P()
	g.P("\tif resp == nil {")
	g.P("\t\treturn nil")
	g.P("\t}")
	g.P("\tif len(respBody) == 0 {")
	g.P("\t\treturn nil")
	g.P("\t}")
	g.P("\tif err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respBody, resp); err != nil {")
	g.P("\t\treturn fmt.Errorf(\"unmarshal response: %w\", err)")
	g.P("\t}")
	g.P("\treturn nil")
	g.P("}")
	g.P()

	for _, service := range file.Services {
		generateServiceClient(g, service)
	}
}

func generateServiceClient(g *protogen.GeneratedFile, service *protogen.Service) {
	clientName := service.GoName + "Client"
	serviceInterface := service.GoName
	servicePath := "kebabCaseServicePath(\"" + service.GoName + "\")"

	g.P("type ", clientName, " struct {")
	g.P("\tbaseURL       string")
	g.P("\tservicePath   string")
	g.P("\thttpClient    *http.Client")
	g.P("\ttokenProvider BearerTokenProvider")
	g.P("}")
	g.P()

	g.P("func New", clientName, "(baseURL string, opts ...ClientOption) *", clientName, " {")
	g.P("\to := &clientOptions{httpClient: &http.Client{}}")
	g.P("\tfor _, opt := range opts {")
	g.P("\t\tif opt != nil {")
	g.P("\t\t\topt(o)")
	g.P("\t\t}")
	g.P("\t}")
	g.P("\treturn &", clientName, "{")
	g.P("\t\tbaseURL:       normalizeBaseURL(baseURL),")
	g.P("\t\tservicePath:   ", servicePath, ",")
	g.P("\t\thttpClient:    o.httpClient,")
	g.P("\t\ttokenProvider: o.tokenProvider,")
	g.P("\t}")
	g.P("}")
	g.P()

	g.P("var _ ", serviceInterface, " = (*", clientName, ")(nil)")
	g.P()

	for _, method := range service.Methods {
		input := g.QualifiedGoIdent(method.Input.GoIdent)
		output := g.QualifiedGoIdent(method.Output.GoIdent)
		methodName := method.GoName

		g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, req *", input, ") (*", output, ", error) {")
		g.P("\tif req == nil {")
		g.P("\t\treturn nil, fmt.Errorf(\"request is required\")")
		g.P("\t}")
		g.P("\tresp := &", output, "{}")
		g.P("\tif err := doProtoJSONCall(ctx, c.httpClient, c.tokenProvider, c.baseURL, c.servicePath, \"", methodName, "\", req, resp); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn resp, nil")
		g.P("}")
		g.P()
	}
}

func generateServiceClientExternal(g *protogen.GeneratedFile, file *protogen.File, service *protogen.Service) {
	clientName := service.GoName + "Client"
	serviceInterface := g.QualifiedGoIdent(protogen.GoIdent{GoName: service.GoName, GoImportPath: file.GoImportPath})
	servicePath := "kebabCaseServicePath(\"" + service.GoName + "\")"

	g.P("type ", clientName, " struct {")
	g.P("\tbaseURL       string")
	g.P("\tservicePath   string")
	g.P("\thttpClient    *http.Client")
	g.P("\ttokenProvider BearerTokenProvider")
	g.P("}")
	g.P()

	g.P("func New", clientName, "(baseURL string, opts ...ClientOption) *", clientName, " {")
	g.P("\to := &clientOptions{httpClient: &http.Client{}}")
	g.P("\tfor _, opt := range opts {")
	g.P("\t\tif opt != nil {")
	g.P("\t\t\topt(o)")
	g.P("\t\t}")
	g.P("\t}")
	g.P("\treturn &", clientName, "{")
	g.P("\t\tbaseURL:       normalizeBaseURL(baseURL),")
	g.P("\t\tservicePath:   ", servicePath, ",")
	g.P("\t\thttpClient:    o.httpClient,")
	g.P("\t\ttokenProvider: o.tokenProvider,")
	g.P("\t}")
	g.P("}")
	g.P()

	g.P("var _ ", serviceInterface, " = (*", clientName, ")(nil)")
	g.P()

	for _, method := range service.Methods {
		input := g.QualifiedGoIdent(method.Input.GoIdent)
		output := g.QualifiedGoIdent(method.Output.GoIdent)
		methodName := method.GoName

		g.P("func (c *", clientName, ") ", methodName, "(ctx context.Context, req *", input, ") (*", output, ", error) {")
		g.P("\tif req == nil {")
		g.P("\t\treturn nil, fmt.Errorf(\"request is required\")")
		g.P("\t}")
		g.P("\tresp := &", output, "{}")
		g.P("\tif err := doProtoJSONCall(ctx, c.httpClient, c.tokenProvider, c.baseURL, c.servicePath, \"", methodName, "\", req, resp); err != nil {")
		g.P("\t\treturn nil, err")
		g.P("\t}")
		g.P("\treturn resp, nil")
		g.P("}")
		g.P()
	}
}

// Keep unused imports safe in older protoc/plugin combinations.
var _ = fmt.Sprintf
